- name: configure Erlang repos
  ansible.builtin.shell: https://packagecloud.io/install/repositories/{{ component }}/erlang/script.rpm.sh

- name: configure Rabbitmq Repos
  ansible.builtin.shell: https://packagecloud.io/install/repositories/{{component}}/{{ component }}-server/script.rpm.sh

- name: Install Rabiitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: start Rabbitmq server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present