- name: Disable default Redis module
  ansible.builtin.command: dnf module disable redis -y

- name: Enable Redis 7 module
  ansible.builtin.command: dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Replace old value with new value
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Replace old value with new value
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'yes'
    replace: 'no'

- name: Start and enable redis service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true
    daemon_reload: true
