- name: Print Parameter from Parameter Store
  hosts: localhost
  connection: local
  tasks:
    - name: Print Parameter
      ansible.builtin.debug:
        msg="{{ lookup('amazon.aws.aws_ssm', 'roboshop/dev/frontend/catalogue_url', region='us-east-1' ) }}"