- name: Disable default Nginx module
  ansible.builtin.command: dnf module disable nginx -y

- name: Enable Nginx 1.24 module
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: Installing Nginx Server
  ansible.builtin.dnf:
    name:
      - nginx
      - unzip
    state: present

- name: Ensure nginx config directory exists
  ansible.builtin.file:
    path: /etc/nginx/default.d
    state: directory
    mode: '0755'

- name: Remove a directory (and all its contents)
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    mode: '0755'

- name: Download and Extract nginx server content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes
    mode: '0755'

- name: Copy nginx config file with owner and permissions
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
    owner: root
    group: root
    mode: '0644'

- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  changed_when: false

- name: Start and enable nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
