- name: Disable default Nginx module
  ansible.builtin.command: dnf module disable nginx -y

- name: Enable Nginx 1.24 module
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: Installing Nginx Server
  ansible.builtin.dnf:
    name:
      - nginx
      - unzip
    state: present

- name: Ensure html directory exists
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    mode: '0755'

- name: Download and Extract frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: true
    mode: '0755'

- name: Configure Nginx reverse proxy
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  changed_when: false

- name: Restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
