- name: Copy MongoDB Repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: Load schema
  ansible.builtin.shell: >
    mongosh --host {{ mongodb_host | default('mongodb-dev.oneseven.space') }}
    < {{ schema_file | default('/app/db/master-data.js') }}
