- name: Disable default NodeJs module
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable NodeJs 20 module
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install NodeJs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: app_presetup.yaml

- name: Load NodeJs Dependecies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Load Schema Setup
  ansible.builtin.import_tasks:
    file: mongo_schema_setup.yaml
  when: load_schema

- name: Systemd Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yaml
    # systemd_setup