- name: Configuring  NodeJs Repos
  ansible.builtin.shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash
- name: Install NodeJs
  ansible.builtin.yum:
      name: nodejs
      state: installed
- name: 
      
    
    
    

    app_presetup

    echo -e "${colour}Install NodeJS Dependencies${nocolour}"
    cd ${app_path}
    npm install &>> ${log_file}
    status_check $?
    systemd_setup