
- name: Copy SystemD File
  ansible.builtin.copy:
    src: "{{ componet }}.service"
    dest: /etc/systemd/system/{{componet}}.service

- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{ componenet }}"
    state: restarted
    enabled: yes
    daemon-related: yes